### ISSUE TITLE
请教一个小问题

### ISSUE THREAD

**Issue by xiaojun678** [wangbo9719/L-Defense_EFND#1]
![image](https://github.com/wangbo9719/L-Defense_EFND/assets/66132188/174005eb-7b98-40ad-9e20-a80f6f182ea2)
想请问一下这里当yt为false时，p应该等于(1,0)而不是(1,1)？希望能得到你们的解答，谢谢！

**Comment by wangbo9719** [comment]
这是一个撰写失误，此处p应该为(1,0)，非常感谢您的指正，我会在arxiv中进行更新。
